### ISSUE TITLE
Should be named shocktopus

### ISSUE THREAD

**Issue by joehandzik** [BlaineEXE/octopus#35]
This is not a real bug report and you can delete it when you like, but seriously? Matt pointed this out, and I must say that I agree.

**Comment by BlaineEXE** [comment]
@joehandzik definitely a missed opportunity. `sh`ocktopus is catchy. I'm not certain I it to want to be conflated with Yu-Gi-Oh though: http://yugioh.wikia.com/wiki/Shocktopus. Shoctopus (w/o the 'k') is apparently a Dublin-based hard rock band. That's a little more palatable.

I def need a unique name if I want my billion-dollar startup around this to be unique for SEO. ;P
